<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'mautic',
	'db_user' => 'root',
	'db_password' => '2asir',
	'db_backup_tables' => 0,
	'db_backup_prefix' => 'bak_',
	'db_server_version' => '5.7.26',
	'mailer_from_name' => 'Diego Moguer',
	'mailer_from_email' => 'cmsmautic@outlook.es',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => 'b9b5dfb22810f12629a19af1102a926016e21679748f15c69f84149e99a83169',
	'site_url' => 'http://localhost/mautic',
);
